# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nico-agent-ingress
  namespace: nico-agent-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nico-agent.dev.api.fashionaiale.com
      secretName: nico-agent-tls
  rules:
    - host: nico-agent.dev.api.fashionaiale.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nico-agent
                port:
                  number: 80

---
# Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: alexander.rivail@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
