#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nico-agent
  name: nico-agent
  namespace: nico-agent-dev
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nico-agent